resume: true
test_freq: 1
wandb:
  project_name: image-vq-vae
  resume: false
dataset:
  name: stl10
  resize: 64
  batch_size: 64
  num_workers: 2
model:
  name: image-vqvae-prior
  model_dir: checkpoints/vqvae
  arch: GatedPixelCNN
  args:
    code_size: 128
    dim: 128
    n_layers: 15
optimizer:
  lr: 0.0005
  weight_decay: 0
  num_epochs: 50
  grad_clip: 1.0
